### ISSUE TITLE
Error building franka_semantic_components

### ISSUE THREAD

**Issue by Zarnack** [tenfoldpaper/panda_ros2#1]
Hey, 
awesome package! Thank you for the work you already put in. I am currently trying to get it working. Unfrotunately the franka_semantic_components part is not building:
```
/robotic_ws/src/panda_ros2/franka_semantic_components/include/franka_semantic_components/franka_robot_model.hpp:15:10: fatal error: semantic_components/semantic_component_interface.hpp: No such file or directory
   15 | #include "semantic_components/semantic_component_interface.hpp"
```
Adding controller_interface to line 15 in the CMakeLists.txt seems to fix this issue:
```
set(THIS_PACKAGE_INCLUDE_DEPENDS Franka franka_hardware franka_msgs hardware_interface controller_interface rclcpp_lifecycle)
```

**Comment by tenfoldpaper** [comment]
Thanks for reporting on it! I will push a fix to the bug you mentioned.
