### ISSUE TITLE
Error building franka_control2

### ISSUE THREAD

**Issue by Zarnack** [tenfoldpaper/panda_ros2#3]
I encountered an error building the new franka_control2 package. It could not find the `realtime_tools/thread_priority.hpp` incuded in `franka_control2_node.cpp`. 

Adding  `realtime_tools` to the `ament_target_dependencies` part in the CMakeLists.txt seems to fix this issue:

```
ament_target_dependencies(franka_control2_node 
  controller_manager
  Franka
  franka_msgs
  realtime_tools)
```

In addition the `franka_msgs` dependency should be added to the `package.xml` of the `franka_control2` package to not have the chance of _colcon build_ failing when building the workspace for the first time:
`<depend>franka_msgs</depend>`

**Comment by tenfoldpaper** [comment]
Thanks for finding the bug! I will add the fix to the repository.
